### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [Old-Stuff/Piano#6]
Hi,
I have read your work so I decided to creat a logo for you. I hope you like it and you want to use it. I can give you all the formats of the design free. If you want to make changes please specify.

Greetings

piano
![piano](https://user-images.githubusercontent.com/34600369/39441018-88cf3826-4ca4-11e8-8006-b20b29c92832.png)

**Comment by MylesBorins** [comment]
Thank you so much!

This project isn't currently being maintained, but if you would like to submit a PR that includes the logo in the README.md I would gladly land it

**Comment by nunojesus** [comment]
I will prepair the files and I will submit a PR tonighit.

Greetigs

**Comment by nunojesus** [comment]
Hi, can you merge the pull request please, Thanks.

**Comment by nunojesus** [comment]
Since you didnt merge the pull request, Im going to cancel this logo, Greetings
